export const actions = {
    profile: {
        DATA_FETCHED: "PROFILE_DATA_FETCH",
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED_ERROR: "PROFILE_DATA_FETCHED_ERROR",
        USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
        IMAGE_UPLOADED: "PROFILE_IMAGE_UPLOADED",
    }
}